### PR TITLE
Update Spring & Quarkus versions

### PR DESCRIPTION
**Pull request by edeandrea**
Update Quarkus version -> 3.4.1
Update Spring version -> 3.1.4

### CODE REVIEW

**Comment by johnaohara** [comment]
@eric the springboot test is failing: https://github.com/johnaohara/idc-quarkus-labs/actions/runs/6394026420/job/17354589487?pr=6#step:4:146

**Comment by edeandrea** [comment]
@johnaohara All tests pass now. Looks like we ran into https://spring.io/blog/2022/12/14/notice-of-permissions-changes-to-repo-spring-io-january-2023 and had to adjust accordingly.

**Comment by johnaohara** [comment]
@edeandrea please can you rebase and resolve the conflicts now?

**Comment by edeandrea** [comment]
@johnaohara I'm not sure what conflicts need to be resolved? 

image

**Pull request merged**
